### ISSUE TITLE
Bordel.wtf Faucets not working

### ISSUE THREAD

**Issue by cryptotester** [ephemery-testnet/ephemery-resources#11]
https://faucet.bordel.wtf/
not working

Payload: `{"address":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"}`
Response: 500 Server error with this `{"msg":"invalid sender"}`

https://api-faucet.bordel.wtf/ 
not working: 502 Bad Gateway

In both cases https not working. Maybe renewing the SSL certificate will help?
SSL certificate expired on Wednesday, September 11, 2024 at 10:26:42 AM

Hint: PoW faucet  https://ephemery-faucet.pk910.de/ works, but still would be cool to have the one click 32 ETH faucets working...

Cheers

**Comment by taxmeifyoucan** [comment]
Sorry about that, the certificate wasn't renewed and the proxy broke. All fixed now, thanks for the report!
